-- 流水线执行记录
CREATE TABLE pipeline_execution (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    repo_id VARCHAR(128) NOT NULL COMMENT '仓库ID',
    branch VARCHAR(128) NOT NULL COMMENT '分支',
    pipeline_id VARCHAR(128) DEFAULT NULL COMMENT '外部流水线ID',
    run_id VARCHAR(128) DEFAULT NULL COMMENT '执行ID',
    project_type VARCHAR(32) NOT NULL DEFAULT 'JAVA_SERVICE' COMMENT '项目类型',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/RUNNING/SUCCESS/FAILED',
    compile_passed TINYINT DEFAULT NULL COMMENT '编译是否通过',
    test_passed TINYINT DEFAULT NULL COMMENT '测试是否通过',
    review_passed TINYINT DEFAULT NULL COMMENT 'Review是否通过',
    quality_gate_passed TINYINT DEFAULT NULL COMMENT '质量门禁总结果',
    log_url TEXT DEFAULT NULL COMMENT '日志URL',
    error_message TEXT DEFAULT NULL COMMENT '错误信息',
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'WEBHOOK' COMMENT '触发类型: WEBHOOK/MANUAL/AI',
    task_id BIGINT DEFAULT NULL COMMENT '关联AI任务ID',
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX idx_tenant_repo (tenant_id, repo_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='流水线执行记录';

-- 部署记录
CREATE TABLE deployment_record (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    environment_id BIGINT UNSIGNED DEFAULT NULL COMMENT '环境ID',
    repo_id VARCHAR(128) NOT NULL COMMENT '仓库ID',
    branch VARCHAR(128) NOT NULL COMMENT '分支',
    image VARCHAR(256) NOT NULL COMMENT '镜像地址',
    namespace VARCHAR(128) NOT NULL COMMENT 'K8s Namespace',
    deployment_name VARCHAR(128) NOT NULL COMMENT '部署名',
    replicas INT NOT NULL DEFAULT 1 COMMENT '副本数',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/DEPLOYING/RUNNING/FAILED/DESTROYED',
    error_message TEXT DEFAULT NULL COMMENT '错误信息',
    pipeline_execution_id BIGINT DEFAULT NULL COMMENT '关联流水线执行ID',
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX idx_tenant (tenant_id),
    INDEX idx_environment (environment_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='部署记录';

-- 环境状态
CREATE TABLE environment (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    name VARCHAR(64) NOT NULL COMMENT '环境名: dev/staging/prod/temp-xxx',
    env_type VARCHAR(32) NOT NULL COMMENT '类型: FIXED/TEMPORARY',
    namespace VARCHAR(128) NOT NULL COMMENT 'K8s Namespace',
    bound_branch VARCHAR(128) DEFAULT NULL COMMENT '绑定分支',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/DESTROYING/DESTROYED',
    auto_destroy_at DATETIME DEFAULT NULL COMMENT '自动销毁时间（临时环境）',
    repo_id VARCHAR(128) DEFAULT NULL COMMENT '关联仓库ID',
    task_id BIGINT DEFAULT NULL COMMENT '关联AI任务ID',
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX idx_tenant (tenant_id),
    INDEX idx_env_type_status (env_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='环境状态';
