run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosimple
    - gocritic
  disable:
    - exhaustive
    - wrapcheck
    - varnamelen

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - commentFormatting
      - hugeParam
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
    - path: internal/testutil/
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
